apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tc6bpu58p-go 
  janus-idp.io/tekton: tc6bpu58p-go
  backstage.io/kubernetes-id: tc6bpu58p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tc6bpu58p-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml